package com.razash.worldtrivia

object Constants {

    const val USER_NAME: String = "user_name"
    const val FINAL_SCORE: String = "final_score"

    fun getCountries() : ArrayList<Country> {
        val countries = ArrayList<Country>()

        countries.add(Country("אפגניסטן", "קאבול", R.drawable.af))
        countries.add(Country("אלבניה", "טירנה", R.drawable.al))
        countries.add(Country("אלג'יריה", "אלג'יר", R.drawable.dz))
        countries.add(Country("אנדורה", "אנדורה לה ולה", R.drawable.ad))
        countries.add(Country("אנגולה", "לואנדה", R.drawable.ao))
        countries.add(Country("אנטיגואה וברבודה", "סנט ג'ונס", R.drawable.ag))
        countries.add(Country("ארגנטינה", "בואנוס איירס", R.drawable.ar))
        countries.add(Country("ארמניה", "ירוואן", R.drawable.am))
        countries.add(Country("אוסטריה", "וינה", R.drawable.at))
        countries.add(Country("אוסטרליה", "קנברה", R.drawable.au))
        countries.add(Country("אזרבייג'אן", "באקו", R.drawable.az))
        countries.add(Country("איי בהאמה", "נסאו", R.drawable.bs))
        countries.add(Country("בחריין", "מנאמה", R.drawable.bh))
        countries.add(Country("בנגלדש", "דאקה", R.drawable.bd))
        countries.add(Country("ברבדוס", "ברידג'טאון", R.drawable.bb))
        countries.add(Country("בלארוס", "מינסק", R.drawable.by))
        countries.add(Country("בלגיה", "בריסל", R.drawable.be))
        countries.add(Country("בליז", "בלמופן", R.drawable.bz))
        countries.add(Country("בנין", "פורטו-נובו", R.drawable.bj))
        countries.add(Country("בהוטאן", "טימפו", R.drawable.bt))
        countries.add(Country("בוליביה", "סוקרה", R.drawable.bo)) // Old flag?
        countries.add(Country("בוסניה והרצגובינה", "סרייבו", R.drawable.ba))
        countries.add(Country("בוטסואנה", "גאבורונה", R.drawable.bw))
        countries.add(Country("ברזיל", "ברזיליה", R.drawable.br))
        countries.add(Country("ברוניי דארוסלאם", "באנדאר סרי בגאוואן", R.drawable.bn))
        countries.add(Country("בולגריה", "סופיה", R.drawable.bg))
        countries.add(Country("בורקינה פאסו", "אואגדוגו", R.drawable.bf))
        countries.add(Country("בורונדי", "גיטגה", R.drawable.bi))
        countries.add(Country("חוף השנהב", "יאמוסוקרו", R.drawable.ci))
        countries.add(Country("כף ורדה", "פראיה", R.drawable.cv))
        countries.add(Country("קמבודיה", "פנום פן", R.drawable.kh))
        countries.add(Country("קמרון", "יאונדה", R.drawable.cm))
        countries.add(Country("קנדה", "אוטוואה", R.drawable.ca))
        countries.add(Country("הרפובליקה המרכז אפריקאית", "באנגוי", R.drawable.cf))
        //countries.add(Country("צ'אד", "נג'מנה", R.drawable.td))
        countries.add(Country("צ'ילה", "סנטיאגו", R.drawable.cl))
        countries.add(Country("סין", "בייג'ינג", R.drawable.cn))
        countries.add(Country("קולומביה", "בוגוטה", R.drawable.co))
        countries.add(Country("איי קומורו", "מורוני", R.drawable.km))
        countries.add(Country("קונגו", "ברזוויל", R.drawable.cg))
        countries.add(Country("קוסטה ריקה", "סן חוזה", R.drawable.cr)) // Old flag?
        countries.add(Country("קרואטיה", "זאגרב", R.drawable.hr))
        countries.add(Country("קובה", "הוואנה", R.drawable.cu))
        countries.add(Country("קפריסין", "ניקוסיה", R.drawable.cy))
        countries.add(Country("צ'כיה", "פראג", R.drawable.cz))
        countries.add(Country("הרפובליקה העממית של קונגו", "קינשאסה", R.drawable.cd))
        countries.add(Country("דנמרק", "קופנהגן", R.drawable.dk))
        countries.add(Country("ג'יבוטי", "ג'יבוטי", R.drawable.dj))
        countries.add(Country("דומיניקה", "רוסו", R.drawable.dm))
        countries.add(Country("הרפובליקה הדומיניקנית", "סנטו דומינגו", R.drawable.do1))
        countries.add(Country("אקוודור", "קיטו", R.drawable.ec))
        countries.add(Country("מצרים", "קהיר", R.drawable.eg))
        countries.add(Country("אל סלבדור", "סן סלבדור", R.drawable.sv))
        countries.add(Country("גינאה המשוונית", "מלאבו", R.drawable.gq))
        countries.add(Country("אריתריאה", "אסמרה", R.drawable.er))
        countries.add(Country("אסטוניה", "טאלין", R.drawable.ee))
        countries.add(Country("אסוואטיני", "לובמבה", R.drawable.sz))
        countries.add(Country("אתיופיה", "אדיס אבבה", R.drawable.et))
        countries.add(Country("פיג'י", "סובה", R.drawable.fj))
        countries.add(Country("פינלנד", "הלסינקי", R.drawable.fi))
        countries.add(Country("צרפת", "פריז", R.drawable.fr))
        countries.add(Country("גאבון", "ליברוויל", R.drawable.ga))
        countries.add(Country("גמביה", "בנז'ול", R.drawable.gm))
        countries.add(Country("גאורגיה", "טביליסי", R.drawable.ge))
        countries.add(Country("גרמניה", "ברלין", R.drawable.de))
        countries.add(Country("גאנה", "אקרה", R.drawable.gh))
        countries.add(Country("יוון", "אתונה", R.drawable.gr))
        countries.add(Country("גרנדה", "סנט ג'ורג'", R.drawable.gd))
        countries.add(Country("גואטמלה", "גואטמלה", R.drawable.gt))
        countries.add(Country("גינאה", "קונאקרי", R.drawable.gn))
        countries.add(Country("גינאה-ביסאו", "ביסאו", R.drawable.gw))
        countries.add(Country("גויאנה", "ג'ורג'טאון", R.drawable.gy))
        countries.add(Country("האיטי", "פורט או פרינס", R.drawable.ht))
        countries.add(Country("הונדורס", "טגוסיגאלפה", R.drawable.hn))
        countries.add(Country("הונגריה", "בודפשט", R.drawable.hu))
        countries.add(Country("איסלנד", "רייקיאוויק", R.drawable.is1))
        countries.add(Country("הודו", "ניו דלהי", R.drawable.in1))
        countries.add(Country("אינדונזיה", "ג'קארטה", R.drawable.id))
        countries.add(Country("איראן", "טהרן", R.drawable.ir))
        countries.add(Country("עירק", "בגדאד", R.drawable.iq))
        countries.add(Country("אירלנד", "דבלין", R.drawable.ie))
        countries.add(Country("ישראל", "ירושלים", R.drawable.il))
        countries.add(Country("איטליה", "רומא", R.drawable.it))
        countries.add(Country("ג'מייקה", "קינגסטון", R.drawable.jm))
        countries.add(Country("יפן", "טוקיו", R.drawable.jp))
        countries.add(Country("ירדן", "עמאן", R.drawable.jo))
        countries.add(Country("קזחסטן", "אסטנה", R.drawable.kz))
        countries.add(Country("קניה", "ניירובי", R.drawable.ke))
        countries.add(Country("קיריבאטי", "טאראווה", R.drawable.ki))
        countries.add(Country("כוויית", "כווית סיטי", R.drawable.kw))
        countries.add(Country("קירגיזסטן", "בישקק", R.drawable.kg))
        countries.add(Country("לאוס", "ויאנג צ'אן", R.drawable.la))
        countries.add(Country("לטביה", "ריגה", R.drawable.lv))
        countries.add(Country("לבנון", "ביירות", R.drawable.lb))
        countries.add(Country("לסוטו", "מסרו", R.drawable.ls))
        countries.add(Country("ליבריה", "מונרוביה", R.drawable.lr))
        countries.add(Country("לוב", "טריפולי", R.drawable.ly))
        countries.add(Country("ליכטנשטיין", "ואדוז", R.drawable.li))
        countries.add(Country("ליטא", "וילנה", R.drawable.lt))
        countries.add(Country("לוקסמבורג", "לוקסמבורג", R.drawable.lu))
        countries.add(Country("מדגסקר", "אנטננריבו", R.drawable.mg))
        countries.add(Country("מלאווי", "לילונגווה", R.drawable.mw))
        countries.add(Country("מלזיה", "קואלה לומפור", R.drawable.my))
        countries.add(Country("איי המלדיביים", "מאלה", R.drawable.mv))
        countries.add(Country("מאלי", "במקו", R.drawable.ml))
        countries.add(Country("מלטה", "ואלטה", R.drawable.mt))
        countries.add(Country("איי מרשל", "מג'ורו", R.drawable.mh))
        countries.add(Country("מאוריטניה", "נוקאצ'וט", R.drawable.mr))
        countries.add(Country("מאוריציוס", "פורט לואיס", R.drawable.mu))
        countries.add(Country("מקסיקו", "מקסיקו סיטי", R.drawable.mx))
        countries.add(Country("מיקרונזיה", "פאליקיר", R.drawable.fm))
        countries.add(Country("מולדובה", "צ'יסינאו", R.drawable.md))
        countries.add(Country("מונקו", "", R.drawable.mc)) // Country-City
        countries.add(Country("מונגוליה", "אולן בטור", R.drawable.mn))
        countries.add(Country("מונטנגרו", "פודגוריצה", R.drawable.me))
        countries.add(Country("מרוקו", "רבאט", R.drawable.ma))
        countries.add(Country("מוזמביק", "מאפוטו", R.drawable.mz))
        countries.add(Country("מיאנמר (בורמה)", "נייפידאו", R.drawable.mm))
        countries.add(Country("נמיביה", "ווינדהוק", R.drawable.na))
        countries.add(Country("נאורו", "מחוז יארן", R.drawable.nr))
        countries.add(Country("נפאל", "קטמנדו", R.drawable.np))
        countries.add(Country("הולנד", "אמסטרדם", R.drawable.nl))
        countries.add(Country("ניו-זילנד", "ולינגטון", R.drawable.nz))
        countries.add(Country("ניקרגואה", "מנאגווה", R.drawable.ni))
        countries.add(Country("ניז'ר", "ניאמיי", R.drawable.ne))
        countries.add(Country("ניגריה", "אבוג'ה", R.drawable.ng))
        countries.add(Country("קוריאה הצפונית", "פיונגיאנג", R.drawable.kp))
        countries.add(Country("מקדוניה", "סקופיה", R.drawable.mk))
        countries.add(Country("נורווגיה", "אוסלו", R.drawable.no))
        countries.add(Country("עומאן", "מוסקט", R.drawable.om))
        countries.add(Country("פקיסטן", "איסלמאבד", R.drawable.pk))
        countries.add(Country("פלאו", "נגרולמוד", R.drawable.pw))
        countries.add(Country("פנמה", "פנמה", R.drawable.pa))
        countries.add(Country("פפואה גינאה החדשה", "פורט מורסבי", R.drawable.pg))
        countries.add(Country("פרגוואי", "אסונסיון", R.drawable.py))
        countries.add(Country("פרו", "לימה", R.drawable.pe))
        countries.add(Country("הפיליפינים", "מנילה", R.drawable.ph))
        countries.add(Country("פולין", "ורשה", R.drawable.pl))
        countries.add(Country("פורטוגל", "ליסבון", R.drawable.pt))
        countries.add(Country("קטאר", "דוחה", R.drawable.qa))
        countries.add(Country("רומניה", "בוקרשט", R.drawable.ro))
        countries.add(Country("רוסיה", "מוסקבה", R.drawable.ru))
        countries.add(Country("רוואנדה", "קיגאלי", R.drawable.rw))
        countries.add(Country("סנט קיטס ונוויס", "באסטר", R.drawable.kn))
        countries.add(Country("סנט לוסיה", "קאסטריס", R.drawable.lc))
        countries.add(Country("סנט וינסנט והגרנדינים", "קינגסטאון", R.drawable.vc))
        countries.add(Country("סמואה", "אפיה", R.drawable.ws))
        countries.add(Country("סן מרינו", "סן מרינו", R.drawable.sm))
        countries.add(Country("סאו טומה ופרינסיפה", "סאו טומה", R.drawable.st))
        countries.add(Country("ערב הסעודית", "ריאד", R.drawable.sa))
        countries.add(Country("סנגל", "דקר", R.drawable.sn))
        countries.add(Country("סרביה", "בלגרד", R.drawable.rs))
        countries.add(Country("סיישל", "ויקטוריה", R.drawable.sc))
        countries.add(Country("סיירה לאון", "פריטאון", R.drawable.sl))
        countries.add(Country("סינגפור", "", R.drawable.sg)) // Country-City
        countries.add(Country("סלובקיה", "ברטיסלבה", R.drawable.sk))
        countries.add(Country("סלובניה", "לובליאנה", R.drawable.si))
        countries.add(Country("איי שלמה", "הוניארה", R.drawable.sb))
        countries.add(Country("סומליה", "מוגדישו", R.drawable.so))
        countries.add(Country("דרום אפריקה", "פרטוריה", R.drawable.za))
        countries.add(Country("קוריאה הדרומית", "סיאול", R.drawable.kr))
        countries.add(Country("דרום סודן", "ג'ובה", R.drawable.ss))
        countries.add(Country("ספרד", "מדריד", R.drawable.es))
        countries.add(Country("סרי לנקה", "קולומבו", R.drawable.lk))
        countries.add(Country("סודאן", "חרטום", R.drawable.sd))
        countries.add(Country("סורינאם", "פרמריבו", R.drawable.sr))
        countries.add(Country("שוודיה", "סטוקהולם", R.drawable.se))
        countries.add(Country("שווייץ", "ברן", R.drawable.ch))
        countries.add(Country("סוריה", "דמשק", R.drawable.sy))
        countries.add(Country("טג'יקיסטן", "דושאנבה", R.drawable.tj))
        countries.add(Country("טנזניה", "דודומה", R.drawable.tz))
        countries.add(Country("תאילנד", "בנגקוק", R.drawable.th))
        countries.add(Country("מזרח טימור", "דילי", R.drawable.tl))
        countries.add(Country("טוגו", "לומה", R.drawable.tg))
        countries.add(Country("טונגה", "נוקואלופה", R.drawable.to))
        countries.add(Country("טרינידד וטובגו", "פורט אוף ספיין", R.drawable.tt))
        countries.add(Country("תוניסיה", "טוניס", R.drawable.tn))
        countries.add(Country("טורקיה", "אנקרה", R.drawable.tr))
        countries.add(Country("טורקמניסטן", "אשגאבאט", R.drawable.tm))
        countries.add(Country("טובאלו", "פנאפוטי", R.drawable.tv))
        countries.add(Country("אוגנדה", "קמפאלה", R.drawable.ug))
        countries.add(Country("אוקראינה", "קייב", R.drawable.ua))
        countries.add(Country("איחוד האמירויות הערביות", "אבו דאבי", R.drawable.ae))
        countries.add(Country("בריטניה", "לונדון", R.drawable.gb))
        countries.add(Country("ארצות הברית", "וושינגטון", R.drawable.us))
        countries.add(Country("אורוגוואי", "מונטווידאו", R.drawable.uy))
        countries.add(Country("אוזבקיסטן", "", R.drawable.uz))
        countries.add(Country("ונואטו", "פורט וילה", R.drawable.vu))
        countries.add(Country("ונצואלה", "קראקס", R.drawable.ve))
        countries.add(Country("וייטנאם", "האנוי", R.drawable.vn))
        countries.add(Country("תימן", "צנעא", R.drawable.ye))
        countries.add(Country("זמביה", "לוסאקה", R.drawable.zm))
        countries.add(Country("זימבבואה", "הררה", R.drawable.zw))

        return countries
    }

}